(function(c,d){typeof exports=="object"&&typeof module<"u"?d(exports,require("react")):typeof define=="function"&&define.amd?define(["exports","react"],d):(c=typeof globalThis<"u"?globalThis:c||self,d(c.MySDK={},c.React))})(this,function(c,d){"use strict";var g={exports:{}},x={};/**
 * @license React
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var m=d,k=Symbol.for("react.element"),j=Symbol.for("react.fragment"),y=Object.prototype.hasOwnProperty,T=m.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,i={key:!0,ref:!0,__self:!0,__source:!0};function f(r,e,a){var t,l={},u=null,h=null;a!==void 0&&(u=""+a),e.key!==void 0&&(u=""+e.key),e.ref!==void 0&&(h=e.ref);for(t in e)y.call(e,t)&&!i.hasOwnProperty(t)&&(l[t]=e[t]);if(r&&r.defaultProps)for(t in e=r.defaultProps,e)l[t]===void 0&&(l[t]=e[t]);return{$$typeof:k,type:r,key:u,ref:h,props:l,_owner:T.current}}x.Fragment=j,x.jsx=f,x.jsxs=f,g.exports=x;var n=g.exports;const S=async r=>{try{const a=await(await fetch("https://api.example.com/exchange-token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:r})})).json();return console.log("Token obtained from API:",a.token),a.token}catch(e){console.error("Error exchanging token:",e);return}},s=d.createContext(void 0),b=()=>{const r=d.useContext(s);if(!r)throw new Error("useSDK must be used within an SDKProvider");return r},v=({children:r,options:e})=>{const[a,t]=d.useState({language:e==null?void 0:e.language,theme:e==null?void 0:e.theme,token:e==null?void 0:e.token});return d.useEffect(()=>{(async()=>{if(!(e!=null&&e.token)){const u=await S();t(h=>({...h,token:u}))}})()},[e==null?void 0:e.token]),d.useEffect(()=>{t(l=>({...l,language:e==null?void 0:e.language,theme:e==null?void 0:e.theme}))},[e==null?void 0:e.language,e==null?void 0:e.theme]),n.jsx(s.Provider,{value:a,children:r})},_=()=>{const{token:r,language:e,theme:a}=b();return n.jsxs("div",{className:"p-4 bg-white rounded shadow-md",children:[n.jsx("h2",{className:"text-xl font-bold mb-4",children:"SDK Widget Content"}),n.jsxs("p",{children:[n.jsx("strong",{children:"Token:"})," ",r||"N/A"]}),n.jsxs("p",{children:[n.jsx("strong",{children:"Language:"})," ",e||"default"]}),n.jsxs("p",{children:[n.jsx("strong",{children:"Theme:"})," ",a||"default"]})]})},E=({options:r})=>{const e=()=>{r!=null&&r.onExpiredToken&&r.onExpiredToken()};return n.jsxs(v,{options:r,children:[n.jsxs("div",{style:{padding:"20px",border:"1px solid #ccc",borderRadius:"8px",marginBottom:"20px"},children:[n.jsx("h3",{children:"SDK Widget Content"}),n.jsxs("p",{children:["Token: ",(r==null?void 0:r.token)||"N/A"]}),n.jsxs("p",{children:["Language: ",(r==null?void 0:r.language)||"N/A"]}),n.jsxs("p",{children:["Theme: ",(r==null?void 0:r.theme)||"N/A"]}),n.jsx("button",{onClick:e,style:{marginTop:"10px",padding:"8px 16px",backgroundColor:"#dc3545",color:"white",border:"none",borderRadius:"4px",cursor:"pointer"},children:"Trigger Expired Token"})]}),n.jsx(_,{})]})};c.DemoSDK=E,Object.defineProperty(c,Symbol.toStringTag,{value:"Module"})});
