(function(n,o){typeof exports=="object"&&typeof module<"u"?o(exports,require("react")):typeof define=="function"&&define.amd?define(["exports","react"],o):(n=typeof globalThis<"u"?globalThis:n||self,o(n.MySDK={},n.React))})(this,function(n,o){"use strict";let d={};const x=async t=>(d={...t},console.log("SDK configured with initial options:",d),d),g=()=>d;var f={exports:{}},u={};/**
 * @license React
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var m=o,y=Symbol.for("react.element"),k=Symbol.for("react.fragment"),j=Object.prototype.hasOwnProperty,v=m.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,_={key:!0,ref:!0,__self:!0,__source:!0};function h(t,e,c){var r,a={},i=null,l=null;c!==void 0&&(i=""+c),e.key!==void 0&&(i=""+e.key),e.ref!==void 0&&(l=e.ref);for(r in e)j.call(e,r)&&!_.hasOwnProperty(r)&&(a[r]=e[r]);if(t&&t.defaultProps)for(r in e=t.defaultProps,e)a[r]===void 0&&(a[r]=e[r]);return{$$typeof:y,type:t,key:i,ref:l,props:a,_owner:v.current}}u.Fragment=k,u.jsx=h,u.jsxs=h,f.exports=u;var s=f.exports;const D=async()=>{try{const e=await(await fetch("https://api.example.com/exchange-token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({})})).json();return console.log("Token obtained from API:",e.token),e.token}catch(t){console.error("Error exchanging token:",t);return}},S=o.createContext(void 0),K=()=>{const t=o.useContext(S);if(!t)throw new Error("useSDK must be used within an SDKProvider");return t},T=({children:t,options:e})=>{const[c,r]=o.useState({language:e==null?void 0:e.language,theme:e==null?void 0:e.theme,token:e==null?void 0:e.token});return o.useEffect(()=>{(async()=>{if(!(e!=null&&e.token)){const i=await D();r(l=>({...l,token:i}))}})()},[e==null?void 0:e.token]),s.jsx(S.Provider,{value:c,children:t})},w=({token:t,language:e,theme:c})=>s.jsxs("div",{className:"p-4 bg-white rounded shadow-md",children:[s.jsx("h2",{className:"text-xl font-bold mb-4",children:"SDK Widget Content"}),s.jsxs("p",{children:[s.jsx("strong",{children:"Token:"})," ",t||"N/A"]}),s.jsxs("p",{children:[s.jsx("strong",{children:"Language:"})," ",e||"default"]}),s.jsxs("p",{children:[s.jsx("strong",{children:"Theme:"})," ",c||"default"]})]});n.SDKProvider=T,n.Widget=w,n.getSDKOptions=g,n.initGapoSDK=x,n.useSDK=K,Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});
